// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiTw7fQpxcwQFScCeldjVho7rla83g6R4',
    appId: '1:328099014391:web:94bd1e39733121886715f2',
    messagingSenderId: '328099014391',
    projectId: 'reddit-17010',
    authDomain: 'reddit-17010.firebaseapp.com',
    storageBucket: 'reddit-17010.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vWIWAgBZz9qT7KZoF3wIJWtuCHMoVOY',
    appId: '1:328099014391:android:ffb2b8c6184642b16715f2',
    messagingSenderId: '328099014391',
    projectId: 'reddit-17010',
    storageBucket: 'reddit-17010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDduRp4hfB8k96MT9oPtKpjdW35whd8f0Y',
    appId: '1:328099014391:ios:61463001ee86bc046715f2',
    messagingSenderId: '328099014391',
    projectId: 'reddit-17010',
    storageBucket: 'reddit-17010.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDduRp4hfB8k96MT9oPtKpjdW35whd8f0Y',
    appId: '1:328099014391:ios:f528b68b624c74306715f2',
    messagingSenderId: '328099014391',
    projectId: 'reddit-17010',
    storageBucket: 'reddit-17010.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
